version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing Serverless Framework..."
      - npm install -g serverless@latest
      - export PATH=$PATH:$(npm root -g) # Ensures serverless is available globally

  pre_build:
    commands:
      - echo "Setting up environment..."
      - echo "Cleaning cache..."
      - rm -rf ~/.serverless
      - npm cache clean --force
      - npm install
      - echo export SERVERLESS_LICENSE_KEY=$SERVERLESS_LICENSE_KEY

      - echo "Configuring AWS credentials..."
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region us-east-1
      - aws sts get-caller-identity || echo "AWS authentication failed!"

      - echo "Disabling Serverless telemetry..."
      - export SLS_TELEMETRY_DISABLED=1

      # ✅ Verify Serverless Installation
      - echo "Checking Serverless Framework version..."
      - which serverless || echo "Serverless Framework not found!"
      - serverless -v || echo "Failed to get Serverless version"

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Running tests..."
      - npm test || true
      - echo "Deploying with Serverless Framework..."
      
      - |
        if [ "${ENV_NAME}" = "" ]; then
          export ENV_NAME="prod"
        fi
      - serverless deploy -v -s ${ENV_NAME} --debug

  post_build:
    commands:
      - echo "Deployment completed on $(date)"
