version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing Serverless Framework..."
      - npm install -g serverless@latest
      - export PATH=$PATH:$(npm root -g) # Ensures serverless is available globally

  pre_build:
    commands:
      - echo "Setting up environment..."
      - echo "Cleaning cache..."
      - rm -rf ~/.serverless
      - npm cache clean --force
      - npm install
      - echo export SERVERLESS_LICENSE_KEY=$SERVERLESS_LICENSE_KEY

      - echo "Disabling Serverless telemetry..."
      - export SLS_TELEMETRY_DISABLED=1

      # ✅ Verify Serverless Installation
      - echo "Checking Serverless Framework version..."
      - which serverless || echo "Serverless Framework not found!"
      - serverless -v || echo "Failed to get Serverless version"

  build:
    commands:
      - echo "Deployment started on $(date)"
      - echo "Deploying with Serverless Framework..."
      
      - serverless deploy -v -s $ENV_NAME --debug || echo "Serverless deployment failed!"

  post_build:
    commands:
      - echo "Deployment completed on $(date)"
