version: 0.2

phases:
  install:
    runtime-versions:
            nodejs: 18.x
    commands:
      - echo Installing Serverless...
      - npm install -g serverless@latest
  pre_build:
    commands:
      - echo Install source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - echo serverless deploy -v -s $ENV_NAME --debug
      - serverless deploy -s prod --debug
  post_build:
    commands:
      - echo Deployment completed on `date`
